pipeline:
  identifier: Build_hrseber_gosample_1737584046706
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: Candidate_2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1737569394802
        repoName: hrseber/gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    command: go test -coverprofile=coverage.out ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: build_go_app
                  name: Build Go App
                  type: Run
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
                  timeout: ""
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
